name: Production Deployment

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'production'
        type: choice
        options:
        - production
        - staging

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    if: github.event_name == 'release' || github.event.inputs.environment == 'production'

    environment:
      name: production
      url: https://spicyfairytales.com

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: spicy-fairytales/package-lock.json

    - name: Install dependencies
      run: |
        cd spicy-fairytales
        PUPPETEER_SKIP_DOWNLOAD=true npm ci

    - name: Build for production
      run: |
        cd spicy-fairytales
        npm run build -- --configuration production

  deploy-staging:
    runs-on: ubuntu-latest
    if: github.event.inputs.environment == 'staging'

    environment:
      name: staging
      url: https://staging.spicyfairytales.com

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: spicy-fairytales/package-lock.json

    - name: Install dependencies
      run: |
        cd spicy-fairytales
        PUPPETEER_SKIP_DOWNLOAD=true npm ci

    - name: Build for staging
      run: |
        cd spicy-fairytales
        npm run build -- --configuration staging