name: Deploy to Vercel

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup Node.js
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: spicy-fairytales/package-lock.json

      - name: Install dependencies
        run: |
          cd spicy-fairytales
          PUPPETEER_SKIP_DOWNLOAD=true npm ci

      - name: Build for Vercel
        run: |
          cd spicy-fairytales
          npm run build:vercel

      - name: Deploy to Vercel
        # Only deploy if Vercel secrets are configured
        if: ${{ secrets.VERCEL_TOKEN != '' }}
        uses: amondnet/vercel-action@16e87c0a08142b0d0d33b76aeaf20823c381b9b9 # v25.2.0
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
          working-directory: spicy-fairytales